/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GameRunner */

#ifndef _Included_GameRunner
#define _Included_GameRunner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GameRunner
 * Method:    runGame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GameRunner_runGame
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
